import { brandMarkPaths } from "./brandPaths";

/**
 * The LearnThrive mark as inline vector (plan15 Wave 10 section 14.1), replacing the 134 KB PNG.
 * Its two inks come from CSS custom properties (`--brand-ink` navy, `--brand-green`), so one component
 * is correct on the light site, the dark theme and a navy footer without a second asset or a chip
 * behind it. The path data is generated by scripts/trace-brand.mjs from the original raster; do not
 * edit it by hand. Decorative: the link around it carries the accessible name.
 */
export function BrandMark({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox={`0 0 ${brandMarkPaths.width} ${brandMarkPaths.height}`}
      fill="none"
      aria-hidden="true"
      focusable="false"
    >
      <path fill="var(--brand-ink)" fillRule="evenodd" d={brandMarkPaths.navy} />
      <path fill="var(--brand-green)" fillRule="evenodd" d={brandMarkPaths.green} />
    </svg>
  );
}
